server:
  port: 9601
spring:
  application:
    name: cloud-zuul    #为你的应用起个名字，该名字将注册到eureka注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
    healthcheck:
      enabled: true
  instance:
      leaseRenewalIntervalInSeconds: 10
      leaseExpirationDurationInSeconds: 30
zuul:
  routes:
    api:
      path: /api/**
      serviceId: cloud-client2
      
